version: "3"
services:
  nest:
    image: nest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .env:/app/.env

  nginx:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=_
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 8080:80

